# Generated by Django 4.1.2 on 2023-01-10 16:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genres', models.CharField(max_length=150)),
                ('release_date', models.CharField(max_length=15)),
                ('rating', models.FloatField()),
                ('user', models.ManyToManyField(related_name='movie_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
